#pragma once

struct regdefs {
	uint8_t TMC_READ;
	uint8_t TMC_WRITE;
	// Register memory positions
	uint8_t REG_GCONF;
	uint8_t REG_GSTAT;
	uint8_t REG_IFCNT;
	uint8_t REG_SLAVECONF;
	uint8_t REG_IOIN;
	uint8_t REG_OUTPUT;
	uint8_t REG_X_COMPARE;
	uint8_t REG_IHOLD_IRUN;
	uint8_t REG_TPOWERDOWN;
	uint8_t REG_TSTEP;
	uint8_t REG_TPWMTHRS;
	uint8_t REG_TCOOLTHRS;
	uint8_t REG_THIGH;
	uint8_t REG_RAMPMODE;
	uint8_t REG_XACTUAL;
	uint8_t REG_VACTUAL;
	uint8_t REG_VSTART;
	uint8_t REG_A1;
	uint8_t REG_V1;
	uint8_t REG_AMAX;
	uint8_t REG_VMAX;
	uint8_t REG_DMAX;
	uint8_t REG_D1;
	uint8_t REG_VSTOP;
	uint8_t REG_TZEROWAIT;
	uint8_t REG_XTARGET;
	uint8_t REG_VDCMIN;
	uint8_t REG_SW_MODE;
	uint8_t REG_RAMP_STAT;
	uint8_t REG_XLATCH;
	uint8_t REG_ENCMODE;
	uint8_t REG_X_ENC;
	uint8_t REG_ENC_CONST;
	uint8_t REG_ENC_STATUS;
	uint8_t REG_ENC_LATCH;
	uint8_t REG_MSLUT0;
	uint8_t REG_MSLUT1;
	uint8_t REG_MSLUT2;
	uint8_t REG_MSLUT3;
	uint8_t REG_MSLUT4;
	uint8_t REG_MSLUT5;
	uint8_t REG_MSLUT6;
	uint8_t REG_MSLUT7;
	uint8_t REG_MSLUTSEL;
	uint8_t REG_MSLUTSTART;
	uint8_t REG_MSCNT;
	uint8_t REG_MSCURACT;
	uint8_t REG_CHOPCONF;
	uint8_t REG_COOLCONF;
	uint8_t REG_DCCTRL;
	uint8_t REG_DRV_STATUS;
	uint8_t REG_PWMCONF;
	uint8_t REG_PWM_SCALE;
	uint8_t REG_ENCM_CTRL;
	uint8_t REG_LOST_STEPS;
	// TMC2660
	uint8_t REG_DRVCTRL;
	uint8_t REG_SMARTEN;
	uint8_t REG_SGCSCONF;
	uint8_t REG_DRVCONF;
	// SPI_STATUS
	uint8_t RESET_FLAG_bp;
	uint8_t DRIVER_ERROR_bp;
	uint8_t SG2_bp;
	uint8_t STANDSTILL_bp;
	uint32_t RESET_FLAG_bm;
	uint32_t DRIVER_ERROR_bm;
	uint32_t SG2_bm;
	uint32_t STANDSTILL_bm;
	// GCONF
	uint8_t I_SCALE_ANALOG_bp;
	uint8_t INTERNAL_RSENSE_bp;
	uint8_t EN_PWM_MODE_bp;
	uint8_t ENC_COMMUTATION_bp;
	uint8_t SHAFT_bp;
	uint8_t DIAG0_ERROR_bp;
	uint8_t DIAG0_OTPW_bp;
	uint8_t DIAG0_STALL_bp;
	uint8_t DIAG0_STEP_bp;
	uint8_t DIAG1_STALL_bp;
	uint8_t DIAG1_DIR_bp;
	uint8_t DIAG1_INDEX_bp;
	uint8_t DIAG1_ONSTATE_bp;
	uint8_t DIAG1_STEPS_SKIPPED_bp;
	uint8_t DIAG0_INT_PUSHPULL_bp;
	uint8_t DIAG1_POSCOMP_PUSHPULL_bp;
	uint8_t SMALL_HYSTERISIS_bp;
	uint8_t STOP_ENABLE_bp;
	uint8_t DIRECT_MODE_bp;
	uint32_t GCONF_bm;
	uint32_t I_SCALE_ANALOG_bm;
	uint32_t INTERNAL_RSENSE_bm;
	uint32_t EN_PWM_MODE_bm;
	uint32_t ENC_COMMUTATION_bm;
	uint32_t SHAFT_bm;
	uint32_t DIAG0_ERROR_bm;
	uint32_t DIAG0_OTPW_bm;
	uint32_t DIAG0_STALL_bm;
	uint32_t DIAG0_STEP_bm;
	uint32_t DIAG1_STALL_bm;
	uint32_t DIAG1_DIR_bm;
	uint32_t DIAG1_INDEX_bm;
	uint32_t DIAG1_ONSTATE_bm;
	uint32_t DIAG1_STEPS_SKIPPED_bm;
	uint32_t DIAG0_INT_PUSHPULL_bm;
	uint32_t DIAG1_POSCOMP_PUSHPULL_bm;
	uint32_t SMALL_HYSTERISIS_bm;
	uint32_t STOP_ENABLE_bm;
	uint32_t DIRECT_MODE_bm;
	// GSTAT
	uint8_t RESET_bp;
	uint8_t DRV_ERR_bp;
	uint8_t UV_CP_bp;
	uint32_t GSTAT_bm;
	uint32_t RESET_bm;
	uint32_t DRV_ERR_bm;
	uint32_t UV_CP_bm;
	// IFCNT
	uint8_t IFCNT_pb;
	uint32_t IFCNT_bm;
	// SLAVECONF
	uint8_t SLAVECONF_bp;
	uint32_t SLAVECONF_bm;
	uint8_t SENDDELAY_bp;
	uint32_t SENDDELAY_bm;
	// IOIN
	uint8_t REFL_STEP_bp;
	uint8_t REFR_DIR_bp;
	uint8_t ENCB_DCEN_CFG4_bp;
	uint8_t ENCA_DCIN_CFG5_bp;
	uint8_t DRV_ENN_CFG6_bp;
	uint8_t ENC_N_DCO_bp;
	uint8_t SD_MODE_bp;
	uint8_t SWCOMP_IN_bp;
	uint8_t VERSION_bp;
	uint32_t IOIN_bm;
	uint32_t REFL_STEP_bm;
	uint32_t REFR_DIR_bm;
	uint32_t ENCB_DCEN_CFG4_bm;
	uint32_t ENCA_DCIN_CFG5_bm;
	uint32_t DRV_ENN_CFG6_bm;
	uint32_t ENC_N_DCO_bm;
	uint32_t SD_MODE_bm;
	uint32_t SWCOMP_IN_bm;
	uint32_t VERSION_bm;
	// OUTPUT
	uint8_t OUTPUT_bp;
	uint32_t OUTPUT_bm;
	// X_COMPARE
	uint8_t X_COMPARE_bp;
	uint32_t X_COMPARE_bm;
	// IHOLD_IRUN
	uint8_t IHOLD_bp;
	uint8_t IRUN_bp;
	uint8_t IHOLDDELAY_bp;
	uint32_t IHOLD_IRUN_bm;
	uint32_t IHOLD_bm;
	uint32_t IRUN_bm;
	uint32_t IHOLDDELAY_bm;
	// TPOWERDOWN
	uint8_t TPOWERDOWN_bp;
	uint32_t TPOWERDOWN_bm;
	// TSTEP
	uint8_t TSTEP_bp;
	uint32_t TSTEP_bm;
	// TPWMTHRS
	uint8_t TPWMTHRS_bp;
	uint32_t TPWMTHRS_bm;
	// TCOOLTHRS
	uint8_t TCOOLTHRS_bp;
	uint32_t TCOOLTHRS_bm;
	// THIGH
	uint8_t THIGH_bp;
	uint32_t THIGH_bm;
	// RAMPMODE
	uint8_t RAMPMODE_bp;
	uint32_t RAMPMODE_bm;
	// XACTUAL
	uint8_t XACTUAL_bp;
	uint32_t XACTUAL_bm;
	// VACTUAL
	uint8_t VACTUAL_bp;
	uint32_t VACTUAL_bm;
	// VSTART
	uint8_t VSTART_bp;
	uint32_t VSTART_bm;
	// A1
	uint8_t A1_bp;
	uint32_t A1_bm;
	// V1
	uint8_t V1_bp;
	uint32_t V1_bm;
	// AMAX
	uint8_t AMAX_bp;
	uint32_t AMAX_bm;
	// VMAX
	uint8_t VMAX_bp;
	uint32_t VMAX_bm;
	// DMAX
	uint8_t DMAX_bp;
	uint32_t DMAX_bm;
	// D1
	uint8_t D1_bp;
	uint32_t D1_bm;
	// VSTOP
	uint8_t VSTOP_bp;
	uint32_t VSTOP_bm;
	// TZEROWAIT
	uint8_t TZEROWAIT_bp;
	uint32_t TZEROWAIT_bm;
	// XTARGET
	uint8_t XTARGET_bp;
	uint32_t XTARGET_bm;
	// VDCMIN
	uint8_t VDCMIN_bp;
	uint32_t VDCMIN_bm;
	// MSLUT0
	uint8_t MSLUT0_bp;
	uint32_t MSLUT0_bm;
	// MSLUT1
	uint8_t MSLUT1_bp;
	uint32_t MSLUT1_bm;
	// MSLUT2
	uint8_t MSLUT2_bp;
	uint32_t MSLUT2_bm;
	// MSLUT3
	uint8_t MSLUT3_bp;
	uint32_t MSLUT3_bm;
	// MSLUT4
	uint8_t MSLUT4_bp;
	uint32_t MSLUT4_bm;
	// MSLUT5
	uint8_t MSLUT5_bp;
	uint32_t MSLUT5_bm;
	// MSLUT6
	uint8_t MSLUT6_bp;
	uint32_t MSLUT6_bm;
	// MSLUT7
	uint8_t MSLUT7_bp;
	uint32_t MSLUT7_bm;
	// MSLUTSEL
	uint8_t MSLUTSEL_bp;
	uint32_t MSLUTSEL_bm;
	// MSLUTSTART
	uint8_t START_SIN_bp;
	uint8_t START_SIN90_bp;
	uint32_t START_SIN_bm;
	uint32_t START_SIN90_bm;
	// MSCNT
	uint8_t MSCNT_bp;
	uint32_t MSCNT_bm;
	// MSCURACT
	uint8_t CUR_A_bp;
	uint8_t CUR_B_bp;
	uint32_t CUR_A_bm;
	uint32_t CUR_B_bm;
	// SW_MODE
	uint8_t STOP_L_ENABLE_bp;
	uint8_t STOP_R_ENABLE_bp;
	uint8_t POL_STOP_L_bp;
	uint8_t POL_STOP_R_bp;
	uint8_t SWAP_LR_bp;
	uint8_t LATCH_L_ACTIVE_bp;
	uint8_t LATCH_L_INACTIVE_bp;
	uint8_t LATCH_R_ACTIVE_bp;
	uint8_t LATCH_R_INACTIVE_bp;
	uint8_t EN_LATCH_ENCODER_bp;
	uint8_t SG_STOP_bp;
	uint8_t EN_SOFTSTOP_bp;
	uint32_t STOP_L_ENABLE_bm;
	uint32_t STOP_R_ENABLE_bm;
	uint32_t POL_STOP_L_bm;
	uint32_t POL_STOP_R_bm;
	uint32_t SWAP_LR_bm;
	uint32_t LATCH_L_ACTIVE_bm;
	uint32_t LATCH_L_INACTIVE_bm;
	uint32_t LATCH_R_ACTIVE_bm;
	uint32_t LATCH_R_INACTIVE_bm;
	uint32_t EN_LATCH_ENCODER_bm;
	uint32_t SG_STOP_bm;
	uint32_t EN_SOFTSTOP_bm;
	// RAMP_STAT
	uint8_t STATUS_STOP_L_bp;
	uint8_t STATUS_STOP_R_bp;
	uint8_t STATUS_LATCH_L_bp;
	uint8_t STATUS_LATCH_R_bp;
	uint8_t EVENT_STOP_L_bp;
	uint8_t EVENT_STOP_R_bp;
	uint8_t EVENT_STOP_SG_bp;
	uint8_t EVENT_POS_REACHED_bp;
	uint8_t VELOCITY_REACHED_bp;
	uint8_t POSITION_REACHED_bp;
	uint8_t VZERO_bp;
	uint8_t T_ZEROWAIT_ACTIVE_bp;
	uint8_t SECOND_MOVE_bp;
	uint8_t STATUS_SG_bp;
	uint32_t STATUS_STOP_L_bm;
	uint32_t STATUS_STOP_R_bm;
	uint32_t STATUS_LATCH_L_bm;
	uint32_t STATUS_LATCH_R_bm;
	uint32_t EVENT_STOP_L_bm;
	uint32_t EVENT_STOP_R_bm;
	uint32_t EVENT_STOP_SG_bm;
	uint32_t EVENT_POS_REACHED_bm;
	uint32_t VELOCITY_REACHED_bm;
	uint32_t POSITION_REACHED_bm;
	uint32_t VZERO_bm;
	uint32_t T_ZEROWAIT_ACTIVE_bm;
	uint32_t SECOND_MOVE_bm;
	uint32_t STATUS_SG_bm;
	// ENCMODE
	uint8_t POL_A_bp;
	uint8_t POL_B_bp;
	uint8_t POL_N_bp;
	uint8_t IGNORE_AB_bp;
	uint8_t CLR_CONT_bp;
	uint8_t CLR_ONCE_bp;
	uint8_t POS_EDGE_bp;
	uint8_t NEG_EDGE_bp;
	uint8_t CLR_ENC_X_bp;
	uint8_t LATCH_X_ACT_bp;
	uint8_t ENC_SEL_DECIMAL_bp;
	uint32_t POL_A_bm;
	uint32_t POL_B_bm;
	uint32_t POL_N_bm;
	uint32_t IGNORE_AB_bm;
	uint32_t CLR_CONT_bm;
	uint32_t CLR_ONCE_bm;
	uint32_t POS_EDGE_bm;
	uint32_t NEG_EDGE_bm;
	uint32_t CLR_ENC_X_bm;
	uint32_t LATCH_X_ACT_bm;
	uint32_t ENC_SEL_DECIMAL_bm;
	// CHOPCONF
	uint8_t TOFF_bp;
	uint8_t HSTRT_bp;
	uint8_t FD_bp;
	uint8_t HEND_bp;
	uint8_t DISFDCC_bp;
	uint8_t RNDTF_bp;
	uint8_t CHM_bp;
	uint8_t TBL_bp;
	uint8_t VSENSE_bp;
	uint8_t VHIGHFS_bp;
	uint8_t VHIGHCHM_bp;
	uint8_t SYNC_bp;
	uint8_t MRES_bp;
	uint8_t INTPOL_bp;
	uint8_t DEDGE_bp;
	uint8_t DISS2G_bp;
	uint8_t HDEC_bp;
	uint32_t CHOPCONF_bm;
	uint32_t TOFF_bm;
	uint32_t HSTRT_bm;
	uint32_t FD_bm;
	uint32_t HEND_bm;
	uint32_t DISFDCC_bm;
	uint32_t RNDTF_bm;
	uint32_t CHM_bm;
	uint32_t TBL_bm;
	uint32_t VSENSE_bm;
	uint32_t VHIGHFS_bm;
	uint32_t VHIGHCHM_bm;
	uint32_t SYNC_bm;
	uint32_t MRES_bm;
	uint32_t INTPOL_bm;
	uint32_t DEDGE_bm;
	uint32_t DISS2G_bm;
	uint32_t HDEC_bm;
	// COOLCONF
	uint8_t SEMIN_bp;
	uint8_t SEUP_bp;
	uint8_t SEMAX_bp;
	uint8_t SEDN_bp;
	uint8_t SEIMIN_bp;
	uint8_t SGT_bp;
	uint8_t SFILT_bp;
	uint32_t COOLCONF_bm;
	uint32_t SEMIN_bm;
	uint32_t SEUP_bm;
	uint32_t SEMAX_bm;
	uint32_t SEDN_bm;
	uint32_t SEIMIN_bm;
	uint32_t SGT_bm;
	uint32_t SFILT_bm;
	// DCCTRL
	uint8_t DC_TIME_bp;
	uint8_t DC_SG_bp;
	uint32_t DC_TIME_bm;
	uint32_t DC_SG_bm;
	// DRV_STATUS
	uint8_t SG_RESULT_bp;
	uint8_t FSACTIVE_bp;
	uint8_t CS_ACTUAL_bp;
	uint8_t STALLGUARD_bp;
	uint8_t OT_bp;
	uint8_t OTPW_bp;
	uint8_t S2GA_bp;
	uint8_t S2GB_bp;
	uint8_t OLA_bp;
	uint8_t OLB_bp;
	uint8_t STST_bp;
	uint32_t DRV_STATUS_bm;
	uint32_t SG_RESULT_bm;
	uint32_t FSACTIVE_bm;
	uint32_t CS_ACTUAL_bm;
	uint32_t STALLGUARD_bm;
	uint32_t OT_bm;
	uint32_t OTPW_bm;
	uint32_t S2GA_bm;
	uint32_t S2GB_bm;
	uint32_t OLA_bm;
	uint32_t OLB_bm;
	uint32_t STST_bm;
	// PWMCONF
	uint8_t PWM_AMPL_bp;
	uint8_t PWM_GRAD_bp;
	uint8_t PWM_FREQ_bp;
	uint8_t PWM_AUTOSCALE_bp;
	uint8_t PWM_SYMMETRIC_bp;
	uint8_t FREEWHEEL_bp;
	uint32_t PWMCONF_bm;
	uint32_t PWM_AMPL_bm;
	uint32_t PWM_GRAD_bm;
	uint32_t PWM_FREQ_bm;
	uint32_t PWM_AUTOSCALE_bm;
	uint32_t PWM_SYMMETRIC_bm;
	uint32_t FREEWHEEL_bm;
	// PWM_SCALE
	uint8_t PWM_SCALE_bp;
	uint32_t PWM_SCALE_bm;
	// ENCM_CTRL
	uint8_t INV_bp;
	uint8_t MAXSPEED_bp;
	uint32_t INV_bm;
	uint32_t MAXSPEED_bm;
	// LOST_STEPS
	uint8_t LOST_STEPS_bp;
	uint32_t LOST_STEPS_bm;
	// TMC2660: DRVCTRL
	uint8_t PHA_bp;
	uint8_t CA_bp;
	uint8_t PHB_bp;
	uint8_t CB_bp;
	uint32_t PHA_bm;
	uint32_t CA_bm;
	uint32_t PHB_bm;
	uint32_t CB_bm;
	// TMC2660: SGCSCONF
	uint8_t CS_bp;
	uint32_t CS_bm;
	// TMC2660: DRVCONF
	uint8_t TST_bp;
	uint8_t SLPH_bp;
	uint8_t SLPL_bp;
	uint8_t TS2G_bp;
	uint8_t SDOFF_bp;
	uint8_t RDSEL_bp;
	uint32_t TST_bm;
	uint32_t SLPH_bm;
	uint32_t SLPL_bm;
	uint32_t TS2G_bm;
	uint32_t SDOFF_bm;
	uint32_t RDSEL_bm;
	// TMC2660: DRVSTATUS
	uint8_t SG_RESULT_10b_bp;
	uint8_t SG_RESULT_5b_bp;
	uint8_t MSTEP_bp;
	uint8_t SE_bp;
	uint8_t SG_bp;
	uint32_t SG_RESULT_10b_bm;
	uint32_t SG_RESULT_5b_bm;
	uint32_t MSTEP_bm;
	uint32_t SE_bm;
	uint32_t SG_bm;
};